### ISSUE TITLE
On the fly compression

### ISSUE THREAD

**Issue by marcheschi** [aelrou/HyperV_Export#1]
Hi 
is it possible to do on the fly compression ?
I  do not have enough space for the whole image is it possible to compress it on the fly in order to save space, without a temp folder?
Thank you
Paolo

**Comment by aelrou** [comment]
I am unsure how PowerShell could be used to make Microsoft Hyper-V compress an export while it creates it. Seems like a feature that Microsoft would have to implement within the export utility. I would certainly be interested if anyone figures that out though.
